###############
# option
###############
# session
set -g prefix C-b
set -g base-index 1
set -g history-limit 10000

# window
setw -g pane-base-index 1

###############
# keybinding
###############
# basic
bind Q kill-server

# pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind x kill-pane
bind | split-window -h
bind _ split-window -v

# navigation
bind y copy-mode
