###############
# option
###############
# session
set -g prefix C-b
set -g base-index 1
set -g history-limit 10000

# window
setw -g pane-base-index 1

###############
# keybinding
###############
# basic
bind Q kill-server
bind R source-file ~/.config/tmux/tmux.conf \; display -d 1000 'Config reloaded!'

# session
bind d detach-client
bind s choose-session
bind ( switch-client -p
bind ) switch-client -n

# window
bind c new-window
bind n next-window
bind p previous-window
bind w choose-window
bind 0 select-window -t :0
bind 1 select-window -t :1
bind 2 select-window -t :2
bind 3 select-window -t :3
bind 4 select-window -t :4
bind 5 select-window -t :5
bind 6 select-window -t :6
bind 7 select-window -t :7
bind 8 select-window -t :8
bind 9 select-window -t :9
bind '{' swap-window -t -1
bind '}' swap-window -t +1
bind X kill-window

# pane
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind q display-panes
bind H swap-pane -s '{left-of}'
bind J swap-pane -s '{down-of}'
bind K swap-pane -s '{up-of}'
bind L swap-pane -s '{right-of}'
bind x kill-pane

# navigation
bind E run-shell "tmux capture-pane -S - -E - -p -J > /tmp/tmux-pane-#{pane_id}.md && tmux new-window -n pane-view 'nvim /tmp/tmux-pane-#{pane_id}.md; rm -f /tmp/tmux-pane-#{pane_id}.md; tmux select-window -t #{window_id}'"
bind y copy-mode
